config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#index'
  resources :books, only: :show do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    collection do
      get 'search'
      get 'ranking'
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reviews

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    #インデックスで表示する名前の配列の作成。
    params[:view_rates] ? @view_rates = params[:view_rates] : @view_rates = [] #params[:view_rates]がnilの場合は空の配列をセットしてエラーを防ぐ。
    @rate_names = ["-新着- 高評価の本【#{@fundamental_names[@view_rates[0].to_i]}】", "高評価の本【#{@fundamental_names[@view_rates[1].to_i]}】", "世代別おすすめの本【#{@generation_names[@view_rates[2].to_i]}】"]

    #新着好評価(高評価上位10冊から5冊)の表示
    recommendation_new_books_ids = Review.where.not("overall_rate" => 0).group(:book_id).order('average_overall_rate DESC').limit(10).average(:overall_rate).keys
    @recommendation_new_books = recommendation_new_books_ids.map{|id| Book.find(id)}.shuffle[0..4] #新着好評価(高評価上位10冊から5冊)の取得
    @recommendation_new_books_rate_averages = set_rate_ave(@recommendation_new_books) #新着好評価5冊の平均値を取得。
    #好評価(高評価上位10冊から5冊)の表示
    recommendation_all_books_ids = Review.where.not("overall_rate" => 0).group(:book_id).order('average_overall_rate DESC').limit(10).average(:overall_rate).keys
    @recommendation_all_books = recommendation_all_books_ids.map{|id| Book.find(id)}.shuffle[0..4]  #好評価(高評価上位10冊から5冊)の取得
    @recommendation_all_books_rate_averages = set_rate_ave(@recommendation_all_books) #5冊の平均値を取得。
    #世代別高評価(高評価上位10冊から5冊)の表示
    recommendation_generation_books_ids = Review.where.not("younger_20s_rate" => 0).group(:book_id).order('younger_20s_rate DESC').limit(10).average(:younger_20s_rate).keys
    @recommendation_generation_books = recommendation_generation_books_ids.map{|id| Book.find(id)}.shuffle[0..4] #世代別高評価(高評価上位10冊から5冊)の取得
    @recommendation_generation_books_rate_averages = set_rate_ave(@recommendation_generation_books) #5冊の平均値を取得。
  end

  def show
    @book = Book.find(params[:id])
    @reviews = Review.includes(:user).where(book_id: params[:id]).order(updated_at: :desc)#レビューを編集の最新順に表示されるように並び替え
    set_rate_ave_hashs(@reviews) #各評価の平均値のハッシュを取得。
    if user_signed_in? #サインインしている場合のみ@myreviewにセット。
      @myreview = Review.find_by(book_id: params[:id], user_id: current_user.id)
    end
  end

  def search
    @books = Book.includes(:reviews).where('book_title LIKE(?)', "%#{params[:keyword]}%").page(params[:page]).per(10)
    #検索結果件数取得
    @number = Book.where('book_title LIKE(?)', "%#{params[:keyword]}%").length  #検索件数を取得
    set_paginate_values(@books, @number)
    set_ave_hash_arrays(@books)
  end

  def ranking
    #@book_pageは、kaminariで使用するための変数→すべてのレビューから評価0とnilを除外し、本ごとにまとめてoverall_rateの平均値順に並べ、kaminariのメソッドを適用。
    @book_page = Review.where.not(@view_rate => 0).group(:book_id).order("average_#{@view_rate} DESC").page(params[:page]).per(10)
    book_ids = @book_page.average(@view_rate).keys #ここの順番は直感的でない。averageを適用すると平均のハッシュとなってしまうのでその前にkaminariのメソッドを記述。
    @books = book_ids.map{|id| Book.find(id)} #ランキングに表示順の配列を取得。ここでは配列にしてしまっているので、kaminariのメソッドは使用できない。
    @number = Review.where.not(@view_rate => 0).group(:book_id).length #ランキングに表示する本の件数取得
    set_paginate_values(@book_page, @number)
    set_ave_hash_arrays(@books)
  end

  #各本のレート平均値を取得し、ハッシュの配列を返す。
  def set_rate_ave(books)
    averages = []
    books.each do |book|
      averages << {:ave_value => rate_ave_value(book.reviews.where.not("overall_rate" => 0).average(:overall_rate)), :ave_star => rate_ave_star(book.reviews.where.not("overall_rate" => 0).average(:overall_rate))}
    end
    return averages
  end

  def set_paginate_values(books, number)
    @page = params[:page].to_i
    @page = 1 if books.first_page? #1ページのみparams[:page]がnilとなるので、最初のページの場合は1となるようにした。
    @view_start_num = (@page-1)*10 + 1
    @view_end_num = @page*10
    @view_end_num = number if books.last_page?  #最後のページは検索件数まで表示
  end

  #各レートの平均値のハッシュを全ての本における配列で取得するための処理を実施。
  def set_ave_hash_arrays(books)
    if books
      @fundamental_rate_ave_values_array = []
      @fundamental_rate_ave_stars_array = []
      @genetation_rate_ave_values_array = []
      @generation_rate_ave_stars_array = []
      @myreviews = []

      books.each do |book|
        set_rate_ave_hashs(book.reviews)
        @fundamental_rate_ave_values_array << @fundamental_rate_ave_values
        @fundamental_rate_ave_stars_array << @fundamental_rate_ave_stars
        @genetation_rate_ave_values_array << @genetation_rate_ave_values
        @generation_rate_ave_stars_array << @generation_rate_ave_stars
        if user_signed_in? #サインインしていてレビューを書いている場合に@myreviewにセット。その他はnil。
          @myreview = Review.find_by(book_id: book.id, user_id: current_user.id)
        else
          @myreview = nil
        end
        @myreviews << @myreview
      end
    end
  end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_info.html.erb
<div class="book-info-detail clearfix">
  <%# ランキングの時の順位表示 %>
  <% if current_page?(ranking_books_path) %>
    <h2 class="ranking"><%= rank %>位</h2>
  <% end %>
  <h2 class="book-title"><%= book.book_title %></h2>
  <div class="book-info-left">
    <div class="book-image-box2">
      <%= link_to book do image_tag(book.book_img_url , :class =>"book-image2") end %>
    </div>
    <%# レートの星と数字の表示（総合評価を表示） %>
    <div class="show-overall-rate">
      <% if fundamental_rate_values[@view_rate] && fundamental_rate_values[@view_rate] != 0 #評価が存在するかどうか %>
        <div class="show-overall-rate-star">
          <span class="rate rate<%= fundamental_rate_stars[@view_rate] %>"></span>
        </div>
        <div class="show-overall-rate-val">
          <span class=""><%= fundamental_rate_values[@view_rate] %></span>
        </div>
      <% else %>
        <span class="show-no-overall-rate">まだ評価はありません。</span>
      <% end %>
    </div>
  </div>

  <div class="book-info-right clearfix">
    <div class="authors-box">
      <span>著者：</span>
      <% authors = ["スティーブン・R・コヴィー", "フランクリン・コヴィー・ジャパン"] %>
      <% authors.each_with_index do |author, i| %>
        <a href="#"><%= author %></a>
        <% unless authors.length == i+1  %>
          <span>,&nbsp;</span>
        <% end %>
      <% end %>
    </div>

    <div style="">
      <%= link_to 'Amazon 詳細ページへ',book.amazon_detail_url , class: "btn btn-default info-link-button"  %>
    </div>

    <div class="clearfix">
      <%# レビューを書いている場合:myreviewがnilでない場合 %>
      <% if myreview %>
        <div class="book-add-button-box">
          <% if current_page?(edit_book_review_path(book,myreview.id)) %>
            <%= link_to book, method: :get, class: "btn btn-default book-add-button" do %>
            レビュー<br>一覧ページへ
            <% end %>
          <% else %>
          <%= link_to 'レビューを編集',edit_book_review_path(book,myreview.id), method: :get, class: "btn btn-default book-add-button" %>
          <% end %>
        </div>
        <div class="book-add-button-box">
          <%= link_to 'レビューを削除',"/books/#{book.id}/reviews/#{myreview.id}", method: :delete, class: "btn btn-default book-add-button" , data: {confirm: '削除してもいいですか？'}  %>
        </div>
        <div class="book-add-button-box">
          <%= button_tag type: "submit", class: "btn btn-default book-add-button" do %>
            <span>おすすめの本<br>に追加</span>
          <% end %>
        </div>

      <%# レビューを書いていない場合 %>
      <% else %>
        <div class="book-add-button-box">
          <% if current_page?(new_book_review_path(book)) %>
            <%= link_to book, method: :get, class: "btn btn-default book-add-button" do %>
            レビュー<br>一覧ページへ
            <% end %>
          <% else %>
            <%= link_to 'レビューを書く',new_book_review_path(book), method: :get, class: "btn btn-default book-add-button"  %>
          <% end %>
        </div>
        <div class="book-add-button-box">
          <%= button_tag type: "submit", class: "btn btn-default book-add-button" do %>
            <span>読みたい本<br>に追加</span>
          <% end %>
        </div>
        <div class="book-add-button-box">
          <%= button_tag type: "submit", class: "btn btn-default book-add-button" do %>
            <span>読む予定<br>に追加</span>
          <% end %>
        </div>
        <div class="book-add-button-box">
          <%= button_tag type: "submit", class: "btn btn-default book-add-button" do %>
            <span>気になる本<br>に追加</span>
          <% end %>
        </div>
      <% end %>
    </div>
    <h4 style="margin-top:5px;font-weight:bold;">【評価平均】</h4>
    <div class="clearfix" style="margin:5px;">
      <%= render 'books/book_rate_box',  fundamental_rate_stars: fundamental_rate_stars, generation_rate_stars: generation_rate_stars %>
    </div>
  </div>
</div>

app/views/books/_book_rate_box.html.erb
<div class="show-book-rate">
  <%# 基本評価テーブル %>
  <div class="show-basic-rate-contribute">
    <h4 class="show-rate-title">基本評価</h4>
    <% @fundamental_names.zip(@fundamental_rates).each do |fundamental_name, fundamental_rate| %>
      <%# 総合評価の場合のみ太字、背景色が異なるよう記載してある。 %>
      <dl class="show-rate" style=<%= "background-color:mistyrose;" if fundamental_name == "総合評価" %>>
        <dt style=<%= "font-weight:bold;" if fundamental_name == "総合評価" %>><%= fundamental_name %></dt>
        <%= render 'books/rate_small', rate: fundamental_rate_stars[fundamental_rate] %>
      </dl>
    <% end %>
  </div>
  <%# 世代別評価テーブル %>
  <div class="show-generation-rate-contribute">
    <h4 class="show-rate-title">世代別おすすめ度</h4>
    <% @generation_names.zip(@generation_rates).each do |generation_name, generation_rate| %>
      <dl class="show-rate">
        <dt><%= generation_name %></dt>
        <%= render 'books/rate_small', rate: generation_rate_stars[generation_rate] %>
      </dl>
    <% end %>
  </div>
</div>

app/views/books/_index_separator.html.erb
<div class="recommendation-content">
  <div class="recommendation-header">
    <%# num=2のときは世代別の評価なので、ランキングに遷移する場合世代別ということが分かるようにview_gene_rate:という名前で渡す。 %>
    <% if num == 2 %>
      <%= link_to ranking_books_path(view_gene_rate: @view_rates[num]), class: "recommendation-link link-hover-blue" do %>
      <strong class="recommendation-title"> <%= @rate_names[num] %> </strong>
      <span class="recommendation-detail">›ランキングを見る</span>
      <% end %>
    <% else %>
      <%= link_to ranking_books_path(view_fund_rate: @view_rates[num]), class: "recommendation-link link-hover-blue" do %>
      <strong class="recommendation-title"> <%= @rate_names[num] %> </strong>
      <span class="recommendation-detail">›ランキングを見る</span>
      <% end %>
    <% end %>
    <div class="dropdown recommendation-right-dropdown">
      <a href="#" class="" data-toggle="dropdown" role="button" aria-expanded="false">
        <span class="">評価内容を変える▼</span>
      </a>
      <ul class="dropdown-menu" role="menu">
      <% names.each_with_index do |name, i| %>
        <li>
          <%# @view_ratesは前の状態を保持した変数。下記で各評価に応じたリンクを生成 %>
          <% @view_rates[num] = i %>
          <%= link_to "#{name}", root_path(:view_rates => @view_rates ) %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
  <% books.zip(averages).each do |book, average|%>
    <div class="book-image-box1">
      <%= link_to book do image_tag( book.book_img_url ) end %>
      <%# レートの星と数字の表示 %>
      <div class="show-top-rate">
        <%# overall_rateiに評価がある場合のみ星表示 %>
        <% if average[:ave_value] && average[:ave_value] != 0 %>
            <div class="show-top-rate-star">
              <span class="rate-small rate-small<%= average[:ave_star] %>"></span>
            </div>
            <div class="show-top-rate-val">
              <span class=""><%= average[:ave_value] %></span>
            </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/books/_rate_small.html.erb
<dd>
  <% if rate && rate != 0 %>
    <% rate *= 10 if rate < 10 %> <%# rateが10以下のとき(10~50に変換されていなくて、1~5のままのとき)10倍する。 %>
    <span class="rate-small rate-small<%= rate.round %>"></span>
  <% else %><span class="show-no-rate">無評価</span>
  <% end %>
</dd>

app/views/books/index.html.erb
<div class="contents clearfix">
  <!-- 新着の評価が高評価 -->
  <%= render 'books/index_separator',num: 0, names: @fundamental_names, books: @recommendation_new_books, averages: @recommendation_new_books_rate_averages %>

  <!-- 全図書の評価が高評価 -->
  <%= render 'books/index_separator',num: 1, names: @fundamental_names, books: @recommendation_all_books, averages: @recommendation_all_books_rate_averages %>

  <!-- 年代別おすすめ -->
  <%= render 'books/index_separator',num: 2, names: @generation_names, books: @recommendation_generation_books, averages: @recommendation_generation_books_rate_averages %>
</div>

app/views/books/ranking.html.erb
<div class="contents clearfix">
  <div class="result">
    <span>【<%= @view_name %>】ランキング <%= @number %>件中 <%= @view_start_num %>位−<%= @view_end_num %>位</span>
  </div>
  <%# 先頭の本の順位をセット %>
  <% rank = @view_start_num %>
  <% @books.zip(@fundamental_rate_ave_stars_array, @generation_rate_ave_stars_array, @fundamental_rate_ave_values_array, @myreviews).each do |book, fundamental_rate_ave_stars, generation_rate_ave_stars, fundamental_rate_ave_values, myreview| %>
    <%# 本情報の部分テンプレート %>
    <%= render 'books/book_info', book: book, fundamental_rate_stars: fundamental_rate_ave_stars, generation_rate_stars: generation_rate_ave_stars,fundamental_rate_values: fundamental_rate_ave_values, myreview: myreview, rank: rank %>
    <%# 次の本の順位をセット %>
    <% rank += 1 %>
  <% end %>
  <div class="paginate">
    <%= paginate(@book_page) %>
  </div>
</div>

app/views/books/search.html.erb
<div class="contents clearfix">
  <div class="result">
    <span>検索結果 <%= @number %>件中 <%= @view_start_num %>−<%= @view_end_num %>件</span>
  </div>
  <% @books.zip(@fundamental_rate_ave_stars_array, @generation_rate_ave_stars_array, @fundamental_rate_ave_values_array, @myreviews).each do |book, fundamental_rate_ave_stars, generation_rate_ave_stars, fundamental_rate_ave_values, myreview| %>
    <%# 本情報の部分テンプレート %>
    <%= render 'books/book_info', book: book, fundamental_rate_stars: fundamental_rate_ave_stars, generation_rate_stars: generation_rate_ave_stars,fundamental_rate_values: fundamental_rate_ave_values, myreview: myreview %>
  <% end %>
  <div class="paginate">
    <%= paginate(@books) %>
  </div>
</div>

app/views/books/show.html.erb
<div class="contents clearfix">
  <%# 本情報の部分テンプレート %>
  <%= render 'books/book_info', book: @book, fundamental_rate_stars: @fundamental_rate_ave_stars, generation_rate_stars: @generation_rate_ave_stars,fundamental_rate_values: @fundamental_rate_ave_values, myreview: @myreview %>

  <div class="reviews-container">
    <h3 class="headline">◆評価・レビュー</h3>
      <% @reviews.each do |review| %>
        <div class="show-review-rate clearfix">
          <div class="clearfix">
            <div class="show-user">
              投稿者：<%= review.user.nickname %>　初回投稿日：<%= review.created_at.strftime("%Y/%m/%d") %>
              <% if review.created_at.strftime("%Y/%m/%d") != review.updated_at.strftime("%Y/%m/%d") %>
               　最新編集日：<%= review.updated_at.strftime("%Y/%m/%d") %>
              <% end %>
            </div>
            <%# 自分のレビューの場合のみ「編集」「削除」を表示 %>
            <% if @myreview && review.id == @myreview.id %>
            <div class="show-edit">
              <%= link_to '編集',edit_book_review_path(@book,@myreview.id), method: :get, style: "margin-right:5px;"  %>
              <%= link_to '削除',"/books/#{@book.id}/reviews/#{@myreview.id}", method: :delete, class: "" , data: {confirm: '削除してもいいですか？'} , style: "margin-right:5px;" %>
            </div>
            <% end %>
          </div>
          <%= render 'books/book_rate_box',  fundamental_rate_stars: review, generation_rate_stars: review %>
          <div class="show-book-review">
            <h4 class="show-review-title"><%= review.review_title %></h4>
            <div class="show-review">
              <%= simple_format(review.review) %>
            </div>
          </div>
        </div>
      <% end %>
  </div>

</div>